name: Feature request
description: Suggest an enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to add?
  - type: textarea
    id: rationale
    attributes:
      label: Why is this useful for beginners?
