name: json-lint
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate JSON
        run: |
          for file in $(git ls-files '*.json'); do
            echo "Checking $file"
            python -m json.tool $file > /dev/null
          done
