name: participants-schema
on:
  pull_request_target:
    branches: [ main ]
    paths:
      - "showcase/participants/*.json"
      - "schemas/participant.schema.json"
      - ".github/workflows/participants-schema.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # 1) Base repo (main) — for the schema
      - name: Checkout base (main) for schema
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base

      # 2) PR head — for the participant files
      - name: Checkout PR head for changed files
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.f_
