name: participants-schema
on:
  pull_request:
    branches: [ main ]
    paths:
      - "showcase/participants/*.json"
      - "schemas/participant.schema.json"
      - ".github/workflows/participants-schema.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base (main) for schema
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base

      - name: Checkout PR head for changed files
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ajv-cli
        run: npm install -g ajv-cli@5

      - name: Validate participants JSON files
        run: |
          set -e
          SCHEMA="base/schemas/participant.schema.json"
          CHANGED=$(ls pr/showcase/participants/*.json 2>/dev/null || true)
          if [ -z "$CHANGED" ]; then
            echo "No participant JSON files to validate."
            exit 0
          fi
          for f in $CHANGED; do
            echo "Validating $f"
            ajv validate -s "$SCHEMA" -d "$f" --errors=text
          done
