name: PR Labeler

# Use pull_request_target so the job runs with repo permissions
# (safe here because we are NOT checking out/exec'ing PR code)
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            hacktoberfest
            needs review
